vim.opt.relativenumber = false -- Disable relative line numbers
vim.opt.showmode = false -- Don't show the current mode
vim.opt.spell = true -- Enable spell checking
-- vim.opt.incsearch = true -- incremental search
vim.opt.scrolloff = 10
vim.opt.wrap = false
vim.opt.linebreak = true
vim.wo.foldmethod = 'expr'
vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
