vim.g.have_nerd_font = true -- I do have nerd fonts
vim.opt.autochdir = false -- Don't change the current directory to the file's directory
vim.opt.clipboard = 'unnamedplus' -- Sync clipboard between OS and Neovim
vim.opt.completeopt = 'menu,menuone,noselect' -- Options for insert mode completion
vim.opt.conceallevel = 2 -- Conceal irrelevant parts of text
vim.opt.confirm = true -- Ask for confirmation when closing unsaved files
vim.opt.cursorline = true -- Highlight the current line
vim.opt.expandtab = true -- Use spaces instead of tabs
vim.opt.formatoptions = 'jcroqlnt' -- Automatic formatting options
vim.opt.grepformat = '%f:%l:%c:%m' -- Format for quickfix window
vim.opt.grepprg = 'rg --vimgrep' -- Use ripgrep for grepping
vim.opt.hidden = true -- Hide buffers instead of closing them
vim.opt.ignorecase = true -- Case-insensitive searching
vim.opt.inccommand = 'nosplit' -- Show effects of :substitute live
vim.opt.laststatus = 3 -- Always show the status line
vim.opt.list = true -- Show invisible characters
vim.opt.listchars = { -- Customize invisible characters
  tab = '▸ ',
  trail = '·',
  nbsp = '␣',
}
vim.opt.mouse = 'a' -- Enable mouse support
vim.opt.number = true -- Show line numbers
vim.opt.pumblend = 10 -- Blend the popup menu with the background
vim.opt.pumheight = 10 -- Maximum number of items to show in the popup menu
vim.opt.relativenumber = false -- Show relative line numbers
-- vim.opt.scrolloff = 4 -- Lines of context above/below cursor
vim.opt.shiftround = true -- Round indent to a multiple of 'shiftwidth'
vim.opt.shiftwidth = 2 -- Size of an indent
vim.opt.showmode = false -- Don't show the current mode
vim.opt.sidescrolloff = 8 -- Columns of context to the left/right of cursor
vim.opt.signcolumn = 'yes' -- Always show the sign column
vim.opt.smartcase = true -- Case-sensitive searching if uppercase is used
vim.opt.smartindent = true -- Smart auto-indenting
vim.opt.spell = false -- Disable spell checking
vim.opt.splitbelow = true -- New horizontal splits open below the current window
vim.opt.splitright = true -- New vertical splits open to the right of the current window
vim.opt.tabstop = 2 -- Number of spaces a tab counts for
vim.opt.termguicolors = true -- Enable 24-bit RGB color in the TUI
vim.opt.timeoutlen = 300 -- Time in ms to wait for a mapped sequence to complete
vim.opt.undofile = true -- Save undo history
vim.opt.updatetime = 250 -- Time in ms to wait before writing swap file
vim.opt.wildmode = 'longest:full,full' -- Command-line completion mode
vim.opt.winblend = 0 -- Blend the window with the background
